<a href="https://colab.research.google.com/github/Asingh1248/Python-DataScience/blob/master/PythonNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays Basics

In [ ]:
# 1D and 2D array (vertically lake diaplya karta hai)

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [ ]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [ ]:
# 2D array

In [ ]:
my_mat= [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_mat) # 2 set of [] and used to diplay array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Np Array using built in methods

In [ ]:
import numpy as np

In [ ]:
# 1) arrange 

In [ ]:
np.arange(0,10) # like range method 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# 2) zeros

In [ ]:
np.zeros(3) # iD array

array([0., 0., 0.])

In [ ]:
np.zeros((3,4)) # No of rows, no of columns 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 3 ) ones 

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 4 ) linspace evenly spaced no over a specified interval 

In [ ]:
np.linspace(0,5,10)

In [ ]:
np.linspace(0,5,15)

In [ ]:
# 5 ) eye (Identity matrix)

In [ ]:
np.eye(5)

In [ ]:
# 6 ) arrays of random number 

In [ ]:
np.random.rand(5) # of (Uniform Distribution) from 0  to 1

array([0.54218022, 0.11362561, 0.32745384, 0.26831044, 0.25320005])

In [ ]:
np.random.rand(4,4) # Note here : input is no specified tuple 

In [ ]:
# 7 ) Standard Normal Distribution or Gaussian Distribution 

In [ ]:
np.random.randn(4)  # ID array

array([-1.34477855, -1.58671766,  0.15378493, -1.05539254])

In [ ]:
np.random.randn(4,5)

In [ ]:
# 8 ) randint

In [ ]:
np.random.randint(0,100) # 0 is inclusive and 100 is exclusive

97

In [ ]:
np.random.randint(0,100,10)

array([92, 26, 40,  3, 58, 80, 94, 25, 85,  2])

# Useful attributes and methods

In [ ]:
arr = np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#1) reshape method

In [ ]:
arr.reshape(5,5) #ID to 2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(5,10) # Check the No of Elements  then accordingly reshpae

In [ ]:
# 2 ) max , min

In [ ]:
ran_arr = np.random.randint(0,50,10)

In [ ]:
ran_arr

In [ ]:
ran_arr.max()

In [ ]:
ran_arr.min()

In [ ]:
ran_arr.argmax()

In [ ]:
ran_arr.argmin()

In [ ]:
# 3) shape

In [ ]:
arr.shape

In [ ]:
b= arr.reshape(5,5)

In [ ]:
# 4) dtype

In [ ]:
arr.dtype

dtype('int64')

# Numpy Indexing and Selection

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10,21)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[5]

15

In [ ]:
arr[0:5]

In [ ]:
arr[2:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

# BroadCasting Values

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[0:5]=100

In [ ]:
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [ ]:
arr = np.arange(10,21)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
slice_arr = arr[0:6] # Data is not copied into new array its pointing to original arra

In [ ]:
slice_arr

array([10, 11, 12, 13, 14, 15])

In [ ]:
slice_arr[:]=99  #It will also reflect in theorignal array

In [ ]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr  # Broadcasting issue (You can use for your benefit)

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
arr_cp = arr.copy()  # Isssue resolved 

In [ ]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
arr[:]=100 # Select all the elements 

In [ ]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr_cp

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [ ]:
# Practice 

# Indexing a 2D array (Matrix)

In [ ]:
import numpy as np  # Vectorixation of Datset ias per andrew ng

In [ ]:
arr_2d= np.array([[5,10,15],[20,20,25],[30,35,40]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 20, 25],
       [30, 35, 40]])

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[0:2,1:3] #Row range 2 because (Upper bound is excluded), (3 is upper bound its exclude)Column range 

# Conditional selection 

In [ ]:
arr= np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
b= arr > 5 

In [ ]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[b] # imp O/p

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr < 8]

array([0, 1, 2, 3, 4, 5, 6, 7])

# Numpy Operations

In [ ]:
import numpy as np

In [ ]:
# array with array 

In [ ]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr + arr

In [ ]:
arr- arr

In [ ]:
arr * arr

In [ ]:
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# array with scalar operations 

In [ ]:
arr + 100

In [ ]:
arr - 50

In [ ]:
arr * 2

In [ ]:
arr / 10

In [ ]:
1 /arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.min(arr)

0

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])