<a href="https://colab.research.google.com/github/Asingh1248/Python-DataScience/blob/master/PythonFundamentals1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Basics

Introduction to Python Advanced Libarairies

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("Hello World") #Without code  

Hello World


String **basics**

In [ ]:
my_string = 'abcde ghijk'

In [ ]:
my_string[-1]

'k'

In [ ]:
print(my_string[2:])
print(my_string[:10])
print(my_string[:])

cde ghijk
abcde ghij
abcde ghijk


In [ ]:
print(my_string[::3])
print(my_string[::-1])

adgj
kjihg edcba


In [ ]:
name= 'Sam'


In [ ]:
name[0]= 'P'  # String Immutable

In [ ]:
print('P'+name[1:])

Pam


In [ ]:
t= 'Thank you'


Basics of Strings

In [ ]:
t.split()

['Thank', 'you']

Lists 

In [ ]:
l= [1,2,3]

In [ ]:
print(l)

[1, 2, 3]


In [ ]:
fruits=['Apple','Banana','Grapes']

In [ ]:
fruits.remove('Banana')

In [ ]:
fruits

['Apple', 'Grapes']

In [ ]:
# adding the list to another lisr

In [ ]:
alpha = ['A','B','C']
num=[1,2,3]

In [ ]:
alpha.extend(num)

In [ ]:
alpha

['A', 'B', 'C', 1, 2, 3]

In [ ]:
num

[1, 2, 3]

In [ ]:
# Dictionary

In [ ]:
d={"key1":108,'Key2':[1,2,3],"Key3":"String"}

In [ ]:
d

{'Key2': [1, 2, 3], 'Key3': 'String', 'key1': 108}

In [ ]:
d['Key3']

'String'

In [ ]:
# editing dictionary

In [ ]:
d['key1']='new value'

In [ ]:
d

{'Key2': [1, 2, 3], 'Key3': 'String', 'key1': 'new value'}

In [ ]:
d['key4']=400

In [ ]:
d

{'Key2': [1, 2, 3], 'Key3': 'String', 'key1': 'new value', 'key4': 400}

In [ ]:
d.keys()

dict_keys(['key1', 'Key2', 'Key3', 'key4'])

In [ ]:
d.values()

dict_values(['new value', [1, 2, 3], 'String', 400])

In [ ]:
d.items()

dict_items([('key1', 'new value'), ('Key2', [1, 2, 3]), ('Key3', 'String'), ('key4', 400)])

In [ ]:
# Tuples 

In [ ]:
alpha=('A','A','B','B','C','C')

In [ ]:
alpha[-1]

'C'

In [ ]:
alpha.count('B')

2

In [ ]:
alpha.index('B')

2

In [ ]:
# Difference between list and tuple

In [ ]:
l=[1,2,3]
t=(1,2,3)

In [ ]:
l[0]=10
print(l)

[10, 2, 3]


In [ ]:
t[0]=10

In [ ]:
my_set=set()

In [ ]:
my_set.add('Hello')

In [ ]:
print(my_set)

{'Hello'}


In [ ]:
l=[1,2,2,3,3,4,4,5,5]

In [ ]:
set(l)

{2, 3, 10}

# Python Part 2

In [ ]:
10>7 #True or False

True

In [ ]:
# if else

In [ ]:
# for loop

In [ ]:
my_list=[1,2,3,4,5,6,7,8,9,10]

In [ ]:
for i in my_list:
  print(i)

In [ ]:
my_string ='Hello World'

In [ ]:
# Write your own for loop

In [ ]:
# Tuple Unpacking 

In [ ]:
l =[(1,2),(3,4),(5,6)]  

In [ ]:
for a,b in l:
  print(a)

1
3
5


In [ ]:
my_dict ={'key1':100,'key2':200 , 'key3':300}

In [ ]:
for i in my_dict:
  print(i)

In [ ]:
for i in my_dict.items():
  print(i)

In [ ]:
for a,b in my_dict.items():
  print(a,b)

key1 100
key2 200
key3 300


In [ ]:
# Today I understood why to use pass keywords 
#pass Keywords for Place holder we will implement the logic of the for  loop afterwards
# Can be used as Placeholder in Big Pojects


In [ ]:
l = [1,2,3,4,5]

In [ ]:
for i in l :
  # will do it later
print('Code ends here ,will continue later') 

IndentationError: ignored

In [ ]:
for i in l :
  # will do it later
  pass
print('Code ends here,will continue later') 

Code ends here,will continue later


# Useful Functions

In [ ]:
#1) range(5,10,2)

In [ ]:
b=list(range(2,11,3))

In [ ]:
b

[2, 5, 8]

In [ ]:
# 2)enumerate (printing the index na dvalues) Can used for tuple unpacking

In [ ]:
word='Batman'

In [ ]:
for letters in enumerate(word):
  print(letters)

In [ ]:
for a,b in enumerate(word):
  print(a)
  print(b)

In [ ]:
# 3) zip function takes the same number of elements from the list

In [ ]:
list_1 = [1,2,3,4,5,6]
list_2 = ['a','b','c']

In [ ]:
zip(list_1,list_2)

In [ ]:
for a,b in zip(list_1,list_2):
  print(a,b)

1 a
2 b
3 c


In [ ]:
# 4 ) in functions used in dictionary 

In [ ]:
'H' in 'School'

False

In [ ]:
d={'key1':100,'key2':200,'key3':300}

In [ ]:
'key1' in d

True

In [ ]:
200 in d.values()

True

In [ ]:
# 5 ) random library (shuffle , randint )

In [ ]:
from random import shuffle
l=[1,2,3,4,5,6,7,8,9,10]
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
shuffle(l)

In [ ]:
print(l)

[1, 10, 9, 4, 5, 8, 6, 3, 7, 2]


In [ ]:
from random import randint
num=randint(0,100)
print(num)

26


In [ ]:
# 6 input , type ,

In [ ]:
name= input('Entr your name : ')
print('Hello {}'.format(name))

Entr your name : Animesh
Hello Animesh


In [ ]:
dir(__builtin__)   # to view all the built in function 

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter